/*
 * Copyright (C) 2017 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.android.dialer.logging.nano;

/** This file is autogenerated, but javadoc required. */
@SuppressWarnings("hiding")
public final class ContactLookupResult
    extends com.google.protobuf.nano.ExtendableMessageNano<ContactLookupResult> {

  /** This file is autogenerated, but javadoc required. */
  // enum Type
  public interface Type {
    public static final int UNKNOWN_LOOKUP_RESULT_TYPE = 0;
    public static final int NOT_FOUND = 1;
    public static final int LOCAL_CONTACT = 2;
    public static final int LOCAL_CACHE = 3;
    public static final int REMOTE = 4;
    public static final int EMERGENCY = 5;
    public static final int VOICEMAIL = 6;
  }

  private static volatile ContactLookupResult[] _emptyArray;

  public static ContactLookupResult[] emptyArray() {
    // Lazily initializes the empty array
    if (_emptyArray == null) {
      synchronized (com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
        if (_emptyArray == null) {
          _emptyArray = new ContactLookupResult[0];
        }
      }
    }
    return _emptyArray;
  }

  // @@protoc_insertion_point(class_scope:com.android.dialer.logging.ContactLookupResult)

  public ContactLookupResult() {
    clear();
  }

  public ContactLookupResult clear() {
    unknownFieldData = null;
    cachedSize = -1;
    return this;
  }

  @Override
  public ContactLookupResult mergeFrom(com.google.protobuf.nano.CodedInputByteBufferNano input)
      throws java.io.IOException {
    while (true) {
      int tag = input.readTag();
      switch (tag) {
        case 0:
          return this;
        default:
          {
            if (!super.storeUnknownField(input, tag)) {
              return this;
            }
            break;
          }
      }
    }
  }

  public static ContactLookupResult parseFrom(byte[] data)
      throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
    return com.google.protobuf.nano.MessageNano.mergeFrom(new ContactLookupResult(), data);
  }

  public static ContactLookupResult parseFrom(
      com.google.protobuf.nano.CodedInputByteBufferNano input) throws java.io.IOException {
    return new ContactLookupResult().mergeFrom(input);
  }
}
