/*
 * Copyright (C) 2016 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.android.dialer.logging.nano;

/** This file is autogenerated, but javadoc required. */
@SuppressWarnings("hiding")
public final class InteractionEvent
    extends com.google.protobuf.nano.ExtendableMessageNano<InteractionEvent> {

  /** This file is autogenerated, but javadoc required. */
  // enum Type
  public interface Type {
    public static final int UNKNOWN = 0;
    public static final int CALL_BLOCKED = 15;
    public static final int BLOCK_NUMBER_CALL_LOG = 16;
    public static final int BLOCK_NUMBER_CALL_DETAIL = 17;
    public static final int BLOCK_NUMBER_MANAGEMENT_SCREEN = 18;
    public static final int UNBLOCK_NUMBER_CALL_LOG = 19;
    public static final int UNBLOCK_NUMBER_CALL_DETAIL = 20;
    public static final int UNBLOCK_NUMBER_MANAGEMENT_SCREEN = 21;
    public static final int IMPORT_SEND_TO_VOICEMAIL = 22;
    public static final int UNDO_BLOCK_NUMBER = 23;
    public static final int UNDO_UNBLOCK_NUMBER = 24;
  }

  private static volatile InteractionEvent[] _emptyArray;
  public static InteractionEvent[] emptyArray() {
    // Lazily initializes the empty array
    if (_emptyArray == null) {
      synchronized (com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
        if (_emptyArray == null) {
          _emptyArray = new InteractionEvent[0];
        }
      }
    }
    return _emptyArray;
  }

  // @@protoc_insertion_point(class_scope:com.android.dialer.logging.InteractionEvent)

  public InteractionEvent() {
    clear();
  }

  public InteractionEvent clear() {
    unknownFieldData = null;
    cachedSize = -1;
    return this;
  }

  @Override
  public InteractionEvent mergeFrom(com.google.protobuf.nano.CodedInputByteBufferNano input)
      throws java.io.IOException {
    while (true) {
      int tag = input.readTag();
      switch (tag) {
        case 0:
          return this;
        default:
          {
            if (!super.storeUnknownField(input, tag)) {
              return this;
            }
            break;
          }
      }
    }
  }

  public static InteractionEvent parseFrom(byte[] data)
      throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
    return com.google.protobuf.nano.MessageNano.mergeFrom(new InteractionEvent(), data);
  }

  public static InteractionEvent parseFrom(com.google.protobuf.nano.CodedInputByteBufferNano input)
      throws java.io.IOException {
    return new InteractionEvent().mergeFrom(input);
  }
}
