/*
 * Copyright (C) 2017 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.android.dialer.callintent.nano;

/** This file is autogenerated, but javadoc required. */
@SuppressWarnings("hiding")
public final class CallSpecificAppData
    extends com.google.protobuf.nano.ExtendableMessageNano<CallSpecificAppData> {

  private static volatile CallSpecificAppData[] _emptyArray;

  public static CallSpecificAppData[] emptyArray() {
    // Lazily initializes the empty array
    if (_emptyArray == null) {
      synchronized (com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
        if (_emptyArray == null) {
          _emptyArray = new CallSpecificAppData[0];
        }
      }
    }
    return _emptyArray;
  }

  // optional int32 call_initiation_type = 1;
  public int callInitiationType;

  // optional int32 position_of_selected_search_result = 2;
  public int positionOfSelectedSearchResult;

  // optional int32 characters_in_search_string = 3;
  public int charactersInSearchString;

  // @@protoc_insertion_point(class_scope:com.android.dialer.callintent.CallSpecificAppData)

  public CallSpecificAppData() {
    clear();
  }

  public CallSpecificAppData clear() {
    callInitiationType = 0;
    positionOfSelectedSearchResult = 0;
    charactersInSearchString = 0;
    unknownFieldData = null;
    cachedSize = -1;
    return this;
  }

  @Override
  public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
      throws java.io.IOException {
    if (this.callInitiationType != 0) {
      output.writeInt32(1, this.callInitiationType);
    }
    if (this.positionOfSelectedSearchResult != 0) {
      output.writeInt32(2, this.positionOfSelectedSearchResult);
    }
    if (this.charactersInSearchString != 0) {
      output.writeInt32(3, this.charactersInSearchString);
    }
    super.writeTo(output);
  }

  @Override
  protected int computeSerializedSize() {
    int size = super.computeSerializedSize();
    if (this.callInitiationType != 0) {
      size +=
          com.google.protobuf.nano.CodedOutputByteBufferNano.computeInt32Size(
              1, this.callInitiationType);
    }
    if (this.positionOfSelectedSearchResult != 0) {
      size +=
          com.google.protobuf.nano.CodedOutputByteBufferNano.computeInt32Size(
              2, this.positionOfSelectedSearchResult);
    }
    if (this.charactersInSearchString != 0) {
      size +=
          com.google.protobuf.nano.CodedOutputByteBufferNano.computeInt32Size(
              3, this.charactersInSearchString);
    }
    return size;
  }

  @Override
  public CallSpecificAppData mergeFrom(com.google.protobuf.nano.CodedInputByteBufferNano input)
      throws java.io.IOException {
    while (true) {
      int tag = input.readTag();
      switch (tag) {
        case 0:
          return this;
        default:
          {
            if (!super.storeUnknownField(input, tag)) {
              return this;
            }
            break;
          }
        case 8:
          {
            this.callInitiationType = input.readInt32();
            break;
          }
        case 16:
          {
            this.positionOfSelectedSearchResult = input.readInt32();
            break;
          }
        case 24:
          {
            this.charactersInSearchString = input.readInt32();
            break;
          }
      }
    }
  }

  public static CallSpecificAppData parseFrom(byte[] data)
      throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
    return com.google.protobuf.nano.MessageNano.mergeFrom(new CallSpecificAppData(), data);
  }

  public static CallSpecificAppData parseFrom(
      com.google.protobuf.nano.CodedInputByteBufferNano input) throws java.io.IOException {
    return new CallSpecificAppData().mergeFrom(input);
  }
}
