/*
 * Copyright (C) 2017 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.android.dialer.backup.nano;

@SuppressWarnings("hiding")
public final class VoicemailInfo extends
    com.google.protobuf.nano.ExtendableMessageNano<VoicemailInfo> {

  private static volatile VoicemailInfo[] _emptyArray;
  public static VoicemailInfo[] emptyArray() {
    // Lazily initializes the empty array
    if (_emptyArray == null) {
      synchronized (
          com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
        if (_emptyArray == null) {
          _emptyArray = new VoicemailInfo[0];
        }
      }
    }
    return _emptyArray;
  }

  // optional string date = 1;
  public java.lang.String date;

  // optional string deleted = 2;
  public java.lang.String deleted;

  // optional string dirty = 3;
  public java.lang.String dirty;

  // optional string dir_type = 4;
  public java.lang.String dirType;

  // optional string duration = 5;
  public java.lang.String duration;

  // optional string has_content = 6;
  public java.lang.String hasContent;

  // optional string is_read = 7;
  public java.lang.String isRead;

  // optional string item_type = 8;
  public java.lang.String itemType;

  // optional string last_modified = 9;
  public java.lang.String lastModified;

  // optional string mime_type = 10;
  public java.lang.String mimeType;

  // optional string number = 11;
  public java.lang.String number;

  // optional string phone_account_component_name = 12;
  public java.lang.String phoneAccountComponentName;

  // optional string phone_account_id = 13;
  public java.lang.String phoneAccountId;

  // optional string source_data = 14;
  public java.lang.String sourceData;

  // optional string source_package = 15;
  public java.lang.String sourcePackage;

  // optional string transcription = 16;
  public java.lang.String transcription;

  // optional string voicemail_uri = 17;
  public java.lang.String voicemailUri;

  // optional bytes encoded_voicemail_key = 18;
  public byte[] encodedVoicemailKey;

  // optional string archived = 19;
  public java.lang.String archived;

  // @@protoc_insertion_point(class_scope:com.android.dialer.backup.VoicemailInfo)

  public VoicemailInfo() {
    clear();
  }

  public VoicemailInfo clear() {
    date = "";
    deleted = "";
    dirty = "";
    dirType = "";
    duration = "";
    hasContent = "";
    isRead = "";
    itemType = "";
    lastModified = "";
    mimeType = "";
    number = "";
    phoneAccountComponentName = "";
    phoneAccountId = "";
    sourceData = "";
    sourcePackage = "";
    transcription = "";
    voicemailUri = "";
    encodedVoicemailKey = com.google.protobuf.nano.WireFormatNano.EMPTY_BYTES;
    archived = "";
    unknownFieldData = null;
    cachedSize = -1;
    return this;
  }

  @Override
  public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
      throws java.io.IOException {
    if (this.date != null && !this.date.equals("")) {
      output.writeString(1, this.date);
    }
    if (this.deleted != null && !this.deleted.equals("")) {
      output.writeString(2, this.deleted);
    }
    if (this.dirty != null && !this.dirty.equals("")) {
      output.writeString(3, this.dirty);
    }
    if (this.dirType != null && !this.dirType.equals("")) {
      output.writeString(4, this.dirType);
    }
    if (this.duration != null && !this.duration.equals("")) {
      output.writeString(5, this.duration);
    }
    if (this.hasContent != null && !this.hasContent.equals("")) {
      output.writeString(6, this.hasContent);
    }
    if (this.isRead != null && !this.isRead.equals("")) {
      output.writeString(7, this.isRead);
    }
    if (this.itemType != null && !this.itemType.equals("")) {
      output.writeString(8, this.itemType);
    }
    if (this.lastModified != null && !this.lastModified.equals("")) {
      output.writeString(9, this.lastModified);
    }
    if (this.mimeType != null && !this.mimeType.equals("")) {
      output.writeString(10, this.mimeType);
    }
    if (this.number != null && !this.number.equals("")) {
      output.writeString(11, this.number);
    }
    if (this.phoneAccountComponentName != null && !this.phoneAccountComponentName.equals("")) {
      output.writeString(12, this.phoneAccountComponentName);
    }
    if (this.phoneAccountId != null && !this.phoneAccountId.equals("")) {
      output.writeString(13, this.phoneAccountId);
    }
    if (this.sourceData != null && !this.sourceData.equals("")) {
      output.writeString(14, this.sourceData);
    }
    if (this.sourcePackage != null && !this.sourcePackage.equals("")) {
      output.writeString(15, this.sourcePackage);
    }
    if (this.transcription != null && !this.transcription.equals("")) {
      output.writeString(16, this.transcription);
    }
    if (this.voicemailUri != null && !this.voicemailUri.equals("")) {
      output.writeString(17, this.voicemailUri);
    }
    if (!java.util.Arrays.equals(this.encodedVoicemailKey, com.google.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
      output.writeBytes(18, this.encodedVoicemailKey);
    }
    if (this.archived != null && !this.archived.equals("")) {
      output.writeString(19, this.archived);
    }
    super.writeTo(output);
  }

  @Override
  protected int computeSerializedSize() {
    int size = super.computeSerializedSize();
    if (this.date != null && !this.date.equals("")) {
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeStringSize(1, this.date);
    }
    if (this.deleted != null && !this.deleted.equals("")) {
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeStringSize(2, this.deleted);
    }
    if (this.dirty != null && !this.dirty.equals("")) {
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeStringSize(3, this.dirty);
    }
    if (this.dirType != null && !this.dirType.equals("")) {
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeStringSize(4, this.dirType);
    }
    if (this.duration != null && !this.duration.equals("")) {
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeStringSize(5, this.duration);
    }
    if (this.hasContent != null && !this.hasContent.equals("")) {
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeStringSize(6, this.hasContent);
    }
    if (this.isRead != null && !this.isRead.equals("")) {
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeStringSize(7, this.isRead);
    }
    if (this.itemType != null && !this.itemType.equals("")) {
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeStringSize(8, this.itemType);
    }
    if (this.lastModified != null && !this.lastModified.equals("")) {
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeStringSize(9, this.lastModified);
    }
    if (this.mimeType != null && !this.mimeType.equals("")) {
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeStringSize(10, this.mimeType);
    }
    if (this.number != null && !this.number.equals("")) {
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeStringSize(11, this.number);
    }
    if (this.phoneAccountComponentName != null && !this.phoneAccountComponentName.equals("")) {
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeStringSize(12, this.phoneAccountComponentName);
    }
    if (this.phoneAccountId != null && !this.phoneAccountId.equals("")) {
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeStringSize(13, this.phoneAccountId);
    }
    if (this.sourceData != null && !this.sourceData.equals("")) {
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeStringSize(14, this.sourceData);
    }
    if (this.sourcePackage != null && !this.sourcePackage.equals("")) {
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeStringSize(15, this.sourcePackage);
    }
    if (this.transcription != null && !this.transcription.equals("")) {
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeStringSize(16, this.transcription);
    }
    if (this.voicemailUri != null && !this.voicemailUri.equals("")) {
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeStringSize(17, this.voicemailUri);
    }
    if (!java.util.Arrays.equals(this.encodedVoicemailKey, com.google.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeBytesSize(18, this.encodedVoicemailKey);
    }
    if (this.archived != null && !this.archived.equals("")) {
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeStringSize(19, this.archived);
    }
    return size;
  }

  @Override
  public VoicemailInfo mergeFrom(
          com.google.protobuf.nano.CodedInputByteBufferNano input)
      throws java.io.IOException {
    while (true) {
      int tag = input.readTag();
      switch (tag) {
        case 0:
          return this;
        default: {
          if (!super.storeUnknownField(input, tag)) {
            return this;
          }
          break;
        }
        case 10: {
          this.date = input.readString();
          break;
        }
        case 18: {
          this.deleted = input.readString();
          break;
        }
        case 26: {
          this.dirty = input.readString();
          break;
        }
        case 34: {
          this.dirType = input.readString();
          break;
        }
        case 42: {
          this.duration = input.readString();
          break;
        }
        case 50: {
          this.hasContent = input.readString();
          break;
        }
        case 58: {
          this.isRead = input.readString();
          break;
        }
        case 66: {
          this.itemType = input.readString();
          break;
        }
        case 74: {
          this.lastModified = input.readString();
          break;
        }
        case 82: {
          this.mimeType = input.readString();
          break;
        }
        case 90: {
          this.number = input.readString();
          break;
        }
        case 98: {
          this.phoneAccountComponentName = input.readString();
          break;
        }
        case 106: {
          this.phoneAccountId = input.readString();
          break;
        }
        case 114: {
          this.sourceData = input.readString();
          break;
        }
        case 122: {
          this.sourcePackage = input.readString();
          break;
        }
        case 130: {
          this.transcription = input.readString();
          break;
        }
        case 138: {
          this.voicemailUri = input.readString();
          break;
        }
        case 146: {
          this.encodedVoicemailKey = input.readBytes();
          break;
        }
        case 154: {
          this.archived = input.readString();
          break;
        }
      }
    }
  }

  public static VoicemailInfo parseFrom(byte[] data)
      throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
    return com.google.protobuf.nano.MessageNano.mergeFrom(new VoicemailInfo(), data);
  }

  public static VoicemailInfo parseFrom(
          com.google.protobuf.nano.CodedInputByteBufferNano input)
      throws java.io.IOException {
    return new VoicemailInfo().mergeFrom(input);
  }
}
